# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VCfEPRvyuiSTnRfPpsB6tGGfu4gFdR_4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/sample_sales_data.csv')
df

from google.colab import drive
drive.mount('/content/drive')

df.shape

df.info()

df.drop(columns=['Unnamed: 0','transaction_id','timestamp','product_id',])
inplace=True

df





df["category"].value_counts()

df["customer_type"].unique()

df["customer_type"].value_counts()

import pandas as pd
import matplotlib.pyplot as plt

# Data for categories and their counts
data = {
    'category': [
        'fruit', 'vegetables', 'packaged foods', 'baked goods', 'canned foods',
        'refrigerated items', 'kitchen', 'meat', 'dairy', 'beverages', 'cheese',
        'cleaning products', 'baking', 'snacks', 'frozen', 'seafood', 'medicine',
        'baby products', 'condiments and sauces', 'personal care', 'pets', 'spices and herbs'
    ],
    'count': [
        998, 846, 507, 443, 431, 425, 382, 382, 375, 301, 293, 292, 264, 263,
        263, 253, 243, 224, 181, 177, 161, 125
    ]
}

# Create DataFrame
df = pd.DataFrame(data)

# Sort the data by count (optional, for better visualization)
df = df.sort_values(by='count', ascending=False)

# Plot the data
plt.figure(figsize=(10, 8))
plt.barh(df['category'], df['count'], color='skyblue')
plt.xlabel("Number of Purchases")
plt.ylabel("Category")
plt.title("Number of Purchases by Category")
plt.gca().invert_yaxis()  # To have the largest bar on top
plt.show()

df['timestamp'].unique()

df.isnull().sum()

df.drop(columns=['Unnamed: 0'],inplace=True)

df

df.describe()

products_counts = df['customer_type'].value_counts()
products_counts.plot(kind='bar')
plt.ylabel("No of products")
plt.title("Number of Products Bought by Customer Type")
plt.show()

"""\

1. Customer Distribution:
Highest Count (non-member): The 'non-member' category has the highest count with 1601 purchases, indicating that even without a membership, a significant number of customers are still engaging with the product. This could imply that non-members are a substantial portion of your market and might be an untapped opportunity for conversion to higher-tier memberships.

Balanced Middle Tiers: The 'standard,' 'premium,' and 'basic' categories have fairly similar counts (1595, 1590, and 1526, respectively), suggesting a relatively even distribution among these tiers. This could mean that customers are evenly spread across these membership levels, possibly indicating good market segmentation.

Lowest Count (gold): The 'gold' category, despite being a higher-tier membership, has the lowest count with 1517 purchases. This might indicate that the highest membership level is either less popular or potentially less accessible or attractive to the majority of your customer base.

2. Membership Conversion Opportunities:
The large number of non-member purchases could indicate an opportunity for conversion campaigns. For instance, marketing efforts could be directed at converting 'non-members' into 'standard' or 'basic' members, potentially through special offers or highlighting the benefits of membership.** **bold text**

Analyzing the features and benefits of the 'gold' membership tier might help identify why fewer customers are in this category. Perhaps revising the benefits, pricing, or communicating the value more effectively could encourage more customers to upgrade to this level
"""

data = {
    'customer_type': ['non-member', 'standard', 'premium', 'basic', 'gold', 'non-member', 'premium', 'gold', 'basic', 'standard'],
    'category': ['fruit', 'vegetables', 'packaged foods', 'fruit', 'baked goods', 'dairy', 'canned foods', 'meat', 'dairy', 'frozen']
}
df = pd.DataFrame(data)

# Group by 'customer_type' and 'category' to get the count of purchases
grouped = df.groupby(['customer_type', 'category']).size().unstack(fill_value=0)

# Plot the data as a stacked bar chart
grouped.plot(kind='bar', stacked=True, figsize=(10, 7))
plt.ylabel("Number of Purchases")
plt.title("Number of Purchases by Customer Type and Category")
plt.show()

import seaborn as sns

plt.figure(figsize=(12, 8))
sns.heatmap(grouped, annot=True, cmap="YlGnBu", linewidths=.5)
plt.title("Heatmap of Purchases by Customer Type and Category")
plt.xlabel("Category")
plt.ylabel("Customer Type")
plt.show()

"""Non-Members:

High purchases in fruit and dairy.
Indicates that non-members might be shopping for essential and frequently consumed items.

Standard Members:

Shows a balance in vegetables, frozen, and fruit.
This indicates a diverse shopping pattern, possibly reflecting a broader interest in various categories.

Premium Members:
High purchases in packaged foods and dairy.
This may suggest a preference for convenience and ready-to-eat products.

Basic Members:
Significant purchases in fruit and dairy.
Similar to non-members, they might be focused on essentials.

Gold Members:
A preference for baked goods and meat.
Gold members might be more inclined to purchase premium or specialized items.


Diverse Purchasing Patterns:

Standard and premium members exhibit diverse purchasing behavior, engaging with a wide range of categories.
Non-members and basic members focus more on essentials like fruit and dairy.
Specialization in Higher Tiers:

Gold members seem to have specific preferences for premium categories like baked goods and meat, suggesting a higher value-per-purchase strategy.


Non-Members to Basic/Standard:
Non-members are already purchasing essential items. Promoting membership benefits related to these categories could convert them to basic or standard memberships.

Premium to Gold:
Premium members' engagement with packaged foods and dairy could be leveraged by offering exclusive deals on meat or baked goods, encouraging them to upgrade to gold membership.


4. Understand Overall Market Segmentation:
Essentials vs. Specialty:

The data shows a clear split between customers who focus on essential categories (non-members and basic) versus those who also engage with specialty categories (premium and gold).

Market Segmentation Strategy:

Tailor marketing strategies to reflect these segments, offering essentials-focused promotions for lower tiers and specialty product promotions for higher tiers.

5. Assess Customer Loyalty and Engagement:
Loyalty Through Specialized Products:
Gold and premium members may be retained by continuing to offer specialized, high-quality products in categories they frequently purchase.
Non-members might be more transactional, requiring frequent promotions to maintain their engagement.

Conclusion:
This is the  detailed analysis provides a deep understanding of how different customer types engage with various product categories. You can use these insights to tailor marketing strategies, optimize inventory management, and improve customer satisfaction by meeting the specific needs of each customer segment.







"""









